In [11]:
# 1. Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

## 1. Примеры создания массивов
- из обычных списков
- с использованием функций `zeros`, `ones`, `arange`

In [12]:
# Создание массива из списка
py_list = [1, 2, 3, 4]
arr_from_list = np.array(py_list)
arr_from_list

# Используем zeros, ones, arange
arr_zeros = np.zeros((2, 3))    # матрица 2x3 из нулей
arr_ones = np.ones(4)           # вектор длины 4 из единиц
arr_range = np.arange(0, 10, 2) # [0,2,4,6,8]
arr_zeros, arr_ones, arr_range

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([1., 1., 1., 1.]),
 array([0, 2, 4, 6, 8]))

## 2. Демонстрация атрибутов
Выведем форму (`shape`) и тип данных (`dtype`) для одного из массивов.

In [13]:
# shape и dtype
print('arr_from_list:', arr_from_list)
print('shape:', arr_from_list.shape)
print('dtype:', arr_from_list.dtype)

# укажем пример для матрицы
print('\narr_zeros shape:', arr_zeros.shape)
print('arr_zeros dtype:', arr_zeros.dtype)


arr_from_list: [1 2 3 4]
shape: (4,)
dtype: int64

arr_zeros shape: (2, 3)
arr_zeros dtype: float64


## 3. Примеры индексирования и срезов
- получение отдельного элемента
- извлечение подмассива с помощью среза

In [14]:
# Индексирование и срезы
elem = arr_from_list[2]
# срез
sub = arr_range[1:4]

# для матрицы: строка, столбец
mat_elem = arr_zeros[0, 1]
mat_row = arr_zeros[0, :]

elem, sub, mat_elem, mat_row


(np.int64(3), array([2, 4, 6]), np.float64(0.0), array([0., 0., 0.]))

## 5. Векторные операции и базовые статистики
- поэлементное сложение/умножение
- вычисление средней величины (`mean`) и других статистик

In [15]:
# Векторные операции
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# поэлементное сложение и умножение
sum_ab = a + b
prod_ab = a * b

# базовая статистика
mean_a = a.mean()
sum_all = a.sum()
max_b = b.max()

sum_ab, prod_ab, mean_a, sum_all, max_b


(array([5, 7, 9]),
 array([ 4, 10, 18]),
 np.float64(2.0),
 np.int64(6),
 np.int64(6))

### Пояснения
- `np.array` — создаёт массив из списка Python.
- `np.zeros`, `np.ones`, `np.arange` — удобные конструкторы.
- `shape` — кортеж с размерами массива; `dtype` — тип элементов.
- Индексирование начинается с 0; срезы работают как в списках.
- Операции над массивами выполняются поэлементно.


In [16]:
# Небольшой итоговый пример: комбинируем всё
# Создадим случайный массив и посчитаем среднее по столбцам
M = np.arange(1,13).reshape(3,4)
print('M =')
print(M)
print('\nmean по строкам:', M.mean(axis=1))
print('mean по столбцам:', M.mean(axis=0))


M =
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

mean по строкам: [ 2.5  6.5 10.5]
mean по столбцам: [5. 6. 7. 8.]
